//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PARCIALDBEveriflix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cancion()
        {
            this.Contenidoes = new HashSet<Contenido>();
        }
    
        public long Id_Cancion { get; set; }
        public string Nombre { get; set; }
        public System.TimeSpan Duracion { get; set; }
        public string ImgURL { get; set; }
        public Nullable<long> Id_Album { get; set; }
        public long Id_Artista { get; set; }
        public long Id_GeneroCancion { get; set; }
        public long Id_TipoContenido { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Artista Artista { get; set; }
        public virtual GeneroCancion GeneroCancion { get; set; }
        public virtual TipoContenido TipoContenido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contenido> Contenidoes { get; set; }
    }
}
