//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PARCIALDBEveriflix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contenido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contenido()
        {
            this.VotacionContenidoes = new HashSet<VotacionContenido>();
            this.VotacionContenidoes1 = new HashSet<VotacionContenido>();
            this.VotacionContenidoes2 = new HashSet<VotacionContenido>();
            this.VotacionContenidoes3 = new HashSet<VotacionContenido>();
            this.Votoes = new HashSet<Voto>();
        }
    
        public long Id_Contenido { get; set; }
        public Nullable<long> Id_Serie { get; set; }
        public Nullable<long> Id_Pelicula { get; set; }
        public Nullable<long> Id_Cancion { get; set; }
    
        public virtual Cancion Cancion { get; set; }
        public virtual Pelicula Pelicula { get; set; }
        public virtual Serie Serie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VotacionContenido> VotacionContenidoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VotacionContenido> VotacionContenidoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VotacionContenido> VotacionContenidoes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VotacionContenido> VotacionContenidoes3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voto> Votoes { get; set; }
    }
}
