//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PARCIALDBEveriflix.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EveryflixDBEntities : DbContext
    {
        public EveryflixDBEntities()
            : base("name=EveryflixDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<Artista> Artistas { get; set; }
        public virtual DbSet<Cancion> Cancions { get; set; }
        public virtual DbSet<Capitulo> Capituloes { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Clasificacion> Clasificacions { get; set; }
        public virtual DbSet<Contenido> Contenidoes { get; set; }
        public virtual DbSet<Director> Directors { get; set; }
        public virtual DbSet<Disquera> Disqueras { get; set; }
        public virtual DbSet<GeneroCancion> GeneroCancions { get; set; }
        public virtual DbSet<Pelicula> Peliculas { get; set; }
        public virtual DbSet<Productor> Productors { get; set; }
        public virtual DbSet<Seguidor> Seguidors { get; set; }
        public virtual DbSet<Serie> Series { get; set; }
        public virtual DbSet<Temporada> Temporadas { get; set; }
        public virtual DbSet<TipoContenido> TipoContenidoes { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuarios { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<VotacionContenido> VotacionContenidoes { get; set; }
        public virtual DbSet<Voto> Votoes { get; set; }
    }
}
