//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PARCIALDBEveriflix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Serie()
        {
            this.Contenidoes = new HashSet<Contenido>();
            this.Temporadas = new HashSet<Temporada>();
        }
    
        public long Id_Serie { get; set; }
        public string Nombre { get; set; }
        public string ImgURL { get; set; }
        public long Id_Categoria { get; set; }
        public Nullable<long> Id_Productor { get; set; }
        public long Id_Clasificacion { get; set; }
        public Nullable<long> Id_Director { get; set; }
        public long Id_TipoContenido { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Clasificacion Clasificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contenido> Contenidoes { get; set; }
        public virtual Director Director { get; set; }
        public virtual Productor Productor { get; set; }
        public virtual TipoContenido TipoContenido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temporada> Temporadas { get; set; }
    }
}
