//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PARCIALDBEveriflix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VotacionContenido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VotacionContenido()
        {
            this.Votoes = new HashSet<Voto>();
        }
    
        public long Id_VotacionContenido { get; set; }
        public string Nombre { get; set; }
        public long Id_TipoContenido { get; set; }
        public Nullable<long> Id_Contenido1 { get; set; }
        public Nullable<long> Id_Contenido2 { get; set; }
        public Nullable<long> Id_Contenido3 { get; set; }
        public Nullable<long> Id_Contenido4 { get; set; }
    
        public virtual Contenido Contenido { get; set; }
        public virtual Contenido Contenido1 { get; set; }
        public virtual Contenido Contenido2 { get; set; }
        public virtual Contenido Contenido3 { get; set; }
        public virtual TipoContenido TipoContenido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voto> Votoes { get; set; }
    }
}
