//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PARCIALDBEveriflix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voto
    {
        public long Id_Voto { get; set; }
        public long Id_Usuario { get; set; }
        public long Id_Contenido { get; set; }
        public long Id_VotacionContenido { get; set; }
    
        public virtual Contenido Contenido { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual VotacionContenido VotacionContenido { get; set; }
    }
}
